# Generated by Django 4.1.5 on 2023-01-24 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 24, 22, 20, 34, 743793, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
